apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharding-app
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharding
  template:
    metadata:
      labels:
        app: sharding
    spec:
      containers:
      - name: sharding
        image: buddhimah/uuid:v1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MAX_CPU
          value: "1.0"
        - name: MAX_MEMORY
          value: "536870912"   # 0.5GB in bytes
        - name: MAX_IO
          value: "524288000"    # 500MB in bytes
        - name: PROMETHEUS_BASE_URL
          value: "http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090"  # Example K8s service for Prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: sharding-service
  namespace: kong
spec:
  selector:
    app: sharding
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
